spring:
  profiles:
    active:
    - dev
---

server:
   port: 7071
spring:
  profiles: dev
  application:
    name: springcloud-microservice-eurekaclient
eureka:
  client:
    serviceUrl:
      defaultZone: http://springcloud-microservice-eurekaserver-8081:8081/eureka/

---
server:
   port: 7072
spring:
  profiles: prod
  application:
    name: springcloud-microservice-eurekaclient
eureka:
  client:
    serviceUrl:
      defaultZone: http://springcloud-microservice-eurekaserver-8082:8082/eureka/

---
server:
   port: 7073
spring:
  profiles: test
  application:
    name: springcloud-microservice-eurekaclient
eureka:
  client:
    serviceUrl:
      defaultZone: http://springcloud-microservice-eurekaserver-8083:8083/eureka/